// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAgzKgre_0Fmsa1je5WvpfU0w9K-fx698',
    appId: '1:874118815337:web:2ef762c9694fbea2d48cf8',
    messagingSenderId: '874118815337',
    projectId: 'booking-tic-2026',
    authDomain: 'booking-tic-2026.firebaseapp.com',
    storageBucket: 'booking-tic-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzgIyO4nq_SnnnMvqu-GSHzolfyq7tXYg',
    appId: '1:874118815337:android:066f0d899e34d14cd48cf8',
    messagingSenderId: '874118815337',
    projectId: 'booking-tic-2026',
    storageBucket: 'booking-tic-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Tk6v6WkXBMK_vp_GKqPRQ-fIWNnr3xg',
    appId: '1:874118815337:ios:a73983529c16fc40d48cf8',
    messagingSenderId: '874118815337',
    projectId: 'booking-tic-2026',
    storageBucket: 'booking-tic-2026.firebasestorage.app',
    iosBundleId: 'com.example.bookin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Tk6v6WkXBMK_vp_GKqPRQ-fIWNnr3xg',
    appId: '1:874118815337:ios:a73983529c16fc40d48cf8',
    messagingSenderId: '874118815337',
    projectId: 'booking-tic-2026',
    storageBucket: 'booking-tic-2026.firebasestorage.app',
    iosBundleId: 'com.example.bookin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAgzKgre_0Fmsa1je5WvpfU0w9K-fx698',
    appId: '1:874118815337:web:f3abfbc4ebf319fdd48cf8',
    messagingSenderId: '874118815337',
    projectId: 'booking-tic-2026',
    authDomain: 'booking-tic-2026.firebaseapp.com',
    storageBucket: 'booking-tic-2026.firebasestorage.app',
  );
}
